# Generated by Django 2.0 on 2019-12-24 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 24, 21, 20, 19, 159180)),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(upload_to='media'),
        ),
    ]
