# Generated by Django 2.0 on 2019-12-24 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191224_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 24, 21, 21, 50, 874377)),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
