# Generated by Django 2.0 on 2020-01-16 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191224_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 16, 8, 30, 45, 965146)),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.FloatField(default=0),
        ),
    ]
