# Generated by Django 2.0 on 2020-01-16 07:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200116_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Company'),
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 16, 12, 59, 30, 87042)),
        ),
    ]
