# Generated by Django 2.0 on 2020-01-16 07:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200116_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 16, 13, 3, 6, 543426)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='bill_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Bill'),
        ),
    ]
