# Generated by Django 3.0.2 on 2020-01-29 16:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200116_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='phoneNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='shippingAddress',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 29, 21, 39, 3, 701321)),
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Product')),
            ],
        ),
    ]
