# Generated by Django 3.0 on 2020-01-30 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200129_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 30, 8, 41, 5, 253897)),
        ),
    ]
