# Generated by Django 3.0.2 on 2020-02-28 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200220_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 28, 10, 29, 50, 106317)),
        ),
    ]
